export const labOrdersSearchData = [
  {
    id: 1,
    title: 'LAB',
    text: 'Kidney Function Test',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 2,
    title: 'LAB',
    text: 'Liver Function Test',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 3,
    title: 'LAB',
    text: 'Thyroid Function Test',
    isFavourite: false,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 4,
    title: 'LAB',
    text: 'Anemia Panel',
    isFavourite: false,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 5,
    title: 'LAB',
    text: 'Complete Blood Count',
    isFavourite: false,
    icon: 'star_border',
    isSelected: false,
  },
];

export const radOrdersSearchData = [
  {
    id: 1,
    title: 'RAD',
    text: 'MRA Renal with Contrast',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 2,
    title: 'RAD',
    text: 'Chest X ray 2 Views',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 3,
    title: 'RAD',
    text: 'Xray Forearm 2 Views RT',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 4,
    title: 'RAD',
    text: 'USG Pelvic',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 5,
    title: 'RAD',
    text: 'US Doppler Abdomen',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
];

export const procedureSearchData = [
  {
    id: 1,
    title: 'PROC',
    text: 'Aortic Angiogram',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 2,
    title: 'PROC',
    text: 'Carotid Angiogram',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 3,
    title: 'PROC',
    text: 'Bronchoscope Rigid Endoscopy',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 4,
    title: 'PROC',
    text: 'ERCP-Endoscopy',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 5,
    title: 'PROC',
    text: 'Colonoscopy',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
];

export const medicationSearchData = [
  {
    id: 1,
    title: 'MED',
    text: 'Concor 2.5 mg Daily',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 2,
    title: 'MED',
    text: 'Rocephin 2g Q24h',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 3,
    title: 'MED',
    text: 'Zyloric 200 mg Once a day',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 4,
    title: 'MED',
    text: 'Panadol 500 mg Twice a day',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 5,
    title: 'MED',
    text: 'Lovenox 40mg Daily',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
  {
    id: 6,
    title: 'MED',
    text: 'Eurok 1 tab Trice a day',
    isFavourite: true,
    icon: 'star_border',
    isSelected: false,
  },
];
