export const environment = {
  production: false,
  brandName: 'kardex',
  LogoUrl: 'assets/logo.png',
  isMultiColorActive: true,
  isDarkSwitchActive: true,
  menuHiddenBreakpoint: 768,
  subHiddenBreakpoint: 1440,
  defaultMenuType: 'menu-default main-hidden sub-hidden',
  defaultColor: 'light.greysteel',
  ver: '1.0.0',
  app_prefix: 'amc_prod_new_',
  client: 300,
  refreshTime :60000,
  DayCaseRefreshTime:900000,
  outPatientRefreshTime:300000,
  emergencyRefreshTime:30000,
  url: 'http://abdaliwebserver.ach.jo:6057/',
  widgetUrl: 'http://abdaliwebserver.ach.jo:6057/',
  eOrderAPIUrl: 'http://abdaliwebserver.ach.jo:6057/',
  eOrderpdfPrint: 'http://achemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDEORDER_SRV/',
  eKardexApiUrl: 'http://abdaliwebserver.ach.jo:6057',
  labChartUrl: 'http://achemr01.ach.jo:8000/sap/bc/ui5_ui5/sap/zn_ish_enav/index.html?sap-client=300&',
  visitNoteUrl: 'http://achemr01.ach.jo:8000/sap/bc/ui5_ui5/sap/zn_ish_enav/index.html?sap-client=300&',
  radiologyUrl: 'https://radportal.ach.jo/portal/?user_name=amcamc&password=amc123&key_images=true&',
};
