export const environment = {
  production: false,
  brandName: 'kardex',
  LogoUrl: 'assets/logo.png',
  isMultiColorActive: true,
  isDarkSwitchActive: true,
  menuHiddenBreakpoint: 768,
  subHiddenBreakpoint: 1440,
  defaultMenuType: 'menu-default main-hidden sub-hidden',
  defaultColor: 'light.greysteel',
  ver: '1.0.0',
  app_prefix: 'amc_dev_',
  client: 210,
  refreshTime :60000,
  DayCaseRefreshTime:900000,
  outPatientRefreshTime:300000,
  emergencyRefreshTime:30000,
  url: 'http://localhost:6052/',
  widgetUrl: 'http://localhost:6052/',
  eOrderAPIUrl: 'http://localhost:6052/',
  eOrderpdfPrint: 'http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDEORDER_SRV/',
  eKardexApiUrl: 'http://localhost:6052',
  labChartUrl: 'http://abdaliwebserver.ach.jo:8090/e-Application-QA/#/home/application?',
  visitNoteUrl: 'http://abdaliwebserver.ach.jo:8090/e-Application-QA/#/home/application?',
  radiologyUrl: 'https://radportal.ach.jo/portal/?user_name=amcamc&password=amc123&key_images=true&',
};