export const environment = {
  production: false,
  brandName: 'kardex',
  LogoUrl: 'assets/logo.png',
  isMultiColorActive: true,
  isDarkSwitchActive: true,
  menuHiddenBreakpoint: 768,
  subHiddenBreakpoint: 1440,
  defaultMenuType: 'menu-default main-hidden sub-hidden',
  defaultColor: 'light.greysteel',
  ver: '1.0.0',
  app_prefix: 'amc_qa_',
  client: 210,
  refreshTime :60000,
  DayCaseRefreshTime:900000,
  outPatientRefreshTime:300000,
  emergencyRefreshTime:30000,
  url: 'http://abdaliwebserver.ach.jo:6051/',
  widgetUrl: 'http://abdaliwebserver.ach.jo:6051/',
  eOrderAPIUrl: 'http://abdaliwebserver.ach.jo:6051/',
  eOrderpdfPrint: 'http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDEORDER_SRV/',
  eKardexApiUrl: 'http://abdaliwebserver.ach.jo:6051',
  labChartUrl: 'http://amcqaemr01.ach.jo:8000/sap/bc/ui5_ui5/sap/zn_ish_enav/index.html?sap-client=210&',
  visitNoteUrl: 'http://amcqaemr01.ach.jo:8000/sap/bc/ui5_ui5/sap/zn_ish_enav/index.html?sap-client=210&',
  radiologyUrl: 'https://radportal.ach.jo/portal/?user_name=amcamc&password=amc123&key_images=true&',
};
// export const environment = {
//   production: false,
//   brandName: 'kardex',
//   LogoUrl: 'assets/logo.png',
//   isMultiColorActive: true,
//   isDarkSwitchActive: true,
//   menuHiddenBreakpoint: 768,
//   subHiddenBreakpoint: 1440,
//   defaultMenuType: 'menu-default main-hidden sub-hidden',
//   defaultColor: 'light.greysteel',
//   ver: '1.0.0',
//   app_prefix: 'amc_qa_',
//   client: 210,
//   refreshTime :60000,
//   DayCaseRefreshTime:900000,
//   outPatientRefreshTime:300000,
//   emergencyRefreshTime:30000,
//   url: '/qa-api/',
//   widgetUrl: '/qa-api/',
//   eOrderAPIUrl: '/qa-api/',
//   eOrderpdfPrint: 'http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZNISHMEDEORDER_SRV/',
//   eKardexApiUrl: '/qa-api',
//   labChartUrl: 'http://amcqaemr01.ach.jo:8000/sap/bc/ui5_ui5/sap/zn_ish_enav/index.html?sap-client=210&',
//   visitNoteUrl: 'http://amcqaemr01.ach.jo:8000/sap/bc/ui5_ui5/sap/zn_ish_enav/index.html?sap-client=210&',
//   radiologyUrl: 'https://radportal.ach.jo/portal/?user_name=amcamc&password=amc123&key_images=true&',
// };
