//Dont Delete this file
export const Dummy = [
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'CARDIOLOGY',
    PersonName: 'DrAhmed',
    Einri: '1000',
    Person: '9000000017',
    Case: '6221',
    CaseType: '3',
    MovementType: 'ER',
    StartDate: '2019-11-06',
    EndDate: null,
    DeptUnit: 'CARMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'CARDIOLOGY',
    PersonName: 'DrAhmed',
    Einri: '1000',
    Person: '9000000017',
    Case: '6221',
    CaseType: '3',
    MovementType: 'MI',
    StartDate: '2028-11-06',
    EndDate: null,
    DeptUnit: 'CARMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'CARDIOLOGY',
    PersonName: 'DrAhmed',
    Einri: '1000',
    Person: '9000000017',
    Case: '6221',
    CaseType: '3',
    MovementType: 'OS',
    StartDate: '2019-11-06',
    EndDate: null,
    DeptUnit: 'CARMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='6221')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'LABORATORY',
    PersonName: 'DrAhmed',
    Einri: '1000',
    Person: '9000000017',
    Case: '6221',
    CaseType: '3',
    MovementType: 'DE',
    StartDate: '2020-09-14',
    EndDate: '2020-09-14',
    DeptUnit: 'LABMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'CARDIOLOGY',
    PersonName: 'Kais Balbissi',
    Einri: '1000',
    Person: '9000000000',
    Case: '7484',
    CaseType: '1',
    MovementType: 'ER',
    StartDate: '2020-07-21',
    EndDate: null,
    DeptUnit: 'CARMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'CARDIOLOGY',
    PersonName: 'Kais Balbissi',
    Einri: '1000',
    Person: '9000000000',
    Case: '7484',
    CaseType: '1',
    MovementType: 'MI',
    StartDate: '2028-07-21',
    EndDate: null,
    DeptUnit: 'CARMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'CARDIOLOGY',
    PersonName: 'Kais Balbissi',
    Einri: '1000',
    Person: '9000000000',
    Case: '7484',
    CaseType: '1',
    MovementType: 'OS',
    StartDate: '2020-07-21',
    EndDate: null,
    DeptUnit: 'CARMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'CARDIOLOGY',
    PersonName: 'Kais Balbissi',
    Einri: '1000',
    Person: '9000000000',
    Case: '7484',
    CaseType: '1',
    MovementType: 'MI',
    StartDate: '2025-07-21',
    EndDate: null,
    DeptUnit: 'CARMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7484')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'LABORATORY',
    PersonName: 'Kais Balbissi',
    Einri: '1000',
    Person: '9000000000',
    Case: '7484',
    CaseType: '1',
    MovementType: 'DE',
    StartDate: '2021-02-24',
    EndDate: '2021-02-24',
    DeptUnit: 'LABMDAMC',
  },
  {
    __metadata: {
      id: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7801')",
      uri: "http://amcqaemr01.ach.jo:8000/sap/opu/odata/sap/ZN_E_KARDEX_SRV/PatientCaseSet(Einri='1000',Case='7801')",
      type: 'ZN_E_KARDEX_SRV.PatientCase',
    },
    Patient: '1',
    DeptUnitName: 'ZQ - Treatment Department',
    PersonName: 'Kais Balbissi',
    Einri: '1000',
    Person: '9000000000',
    Case: '7801',
    CaseType: '2',
    MovementType: 'CO',
    StartDate: '2022-09-01',
    EndDate: null,
    DeptUnit: 'ZQTRTAMC',
  }
];
